# Generated by Django 5.0.7 on 2024-07-19 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('old', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('created_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('obs', models.TextField(blank=True)),
            ],
        ),
    ]
