# Generated by Django 5.0.7 on 2024-07-23 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_aluno_picture_aluno_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('hora_ini', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='old',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Aluno_Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.aluno')),
                ('aula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.aula')),
            ],
        ),
    ]
