# Generated by Django 5.0.7 on 2024-07-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_aluno_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures'),
        ),
    ]
