# Generated by Django 5.0.7 on 2024-07-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_aluno_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/'),
        ),
    ]
