# Generated by Django 5.0.7 on 2024-08-08 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_coach_aluno_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.coach'),
        ),
    ]
