# Generated by Django 5.1 on 2024-08-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='birthday',
            field=models.DateField(blank=True),
        ),
    ]
