# Generated by Django 5.1 on 2024-08-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_alter_aluno_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
