# Generated by Django 5.1 on 2024-08-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_alter_aluno_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='picture',
            field=models.ImageField(blank=True, default='defaults/default.png', null=True, upload_to='pictures/'),
        ),
    ]
