# Generated by Django 5.1 on 2024-08-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_alter_aluno_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='pictures/'),
        ),
    ]
