# Generated by Django 5.1 on 2024-08-20 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0016_alter_aluno_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.CreateModel(
            name='Aluno_OcorrenciaAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='OcorrenciaAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('alunos_presentes', models.ManyToManyField(through='contact.Aluno_OcorrenciaAula', to='contact.aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.aula')),
            ],
        ),
        migrations.AddField(
            model_name='aluno_ocorrenciaaula',
            name='ocorrenciaAula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.ocorrenciaaula'),
        ),
    ]
